# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='model.proto',
  package='chemsim',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bmodel.proto\x12\x07\x63hemsim\"\xfd\x01\n\x05Model\x12\x13\n\x0bmlir_module\x18\x01 \x02(\t\x12\x32\n\rneighbor_list\x18\x04 \x02(\x0b\x32\x1b.chemsim.Model.NeighborList\x1aq\n\x0cNeighborList\x12-\n\x04type\x18\x01 \x02(\x0e\x32\x1f.chemsim.Model.NeighborListType\x12\x0e\n\x06\x63utoff\x18\x02 \x02(\x02\x12\x0f\n\x07num_mpl\x18\x03 \x01(\x05\x12\x11\n\thalf_list\x18\x04 \x01(\x08\"8\n\x10NeighborListType\x12\x11\n\rSIMPLE_SPARSE\x10\x00\x12\x11\n\rDEVICE_SPARSE\x10\x01'
)



_MODEL_NEIGHBORLISTTYPE = _descriptor.EnumDescriptor(
  name='NeighborListType',
  full_name='chemsim.Model.NeighborListType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SIMPLE_SPARSE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEVICE_SPARSE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=222,
  serialized_end=278,
)
_sym_db.RegisterEnumDescriptor(_MODEL_NEIGHBORLISTTYPE)


_MODEL_NEIGHBORLIST = _descriptor.Descriptor(
  name='NeighborList',
  full_name='chemsim.Model.NeighborList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='chemsim.Model.NeighborList.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cutoff', full_name='chemsim.Model.NeighborList.cutoff', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_mpl', full_name='chemsim.Model.NeighborList.num_mpl', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='half_list', full_name='chemsim.Model.NeighborList.half_list', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=220,
)

_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='chemsim.Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mlir_module', full_name='chemsim.Model.mlir_module', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='neighbor_list', full_name='chemsim.Model.neighbor_list', index=1,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MODEL_NEIGHBORLIST, ],
  enum_types=[
    _MODEL_NEIGHBORLISTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=278,
)

_MODEL_NEIGHBORLIST.fields_by_name['type'].enum_type = _MODEL_NEIGHBORLISTTYPE
_MODEL_NEIGHBORLIST.containing_type = _MODEL
_MODEL.fields_by_name['neighbor_list'].message_type = _MODEL_NEIGHBORLIST
_MODEL_NEIGHBORLISTTYPE.containing_type = _MODEL
DESCRIPTOR.message_types_by_name['Model'] = _MODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), {

  'NeighborList' : _reflection.GeneratedProtocolMessageType('NeighborList', (_message.Message,), {
    'DESCRIPTOR' : _MODEL_NEIGHBORLIST,
    '__module__' : 'model_pb2'
    # @@protoc_insertion_point(class_scope:chemsim.Model.NeighborList)
    })
  ,
  'DESCRIPTOR' : _MODEL,
  '__module__' : 'model_pb2'
  # @@protoc_insertion_point(class_scope:chemsim.Model)
  })
_sym_db.RegisterMessage(Model)
_sym_db.RegisterMessage(Model.NeighborList)


# @@protoc_insertion_point(module_scope)
